name: wde
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - anaconda
  - pip
  - pip:
      - torch==2.5.1
      - torchvision==0.20.1
      - transformers==4.45.2
      - fastapi
      - easydict
      - pydantic
      - pyzmq
      - gevent
      - uvicorn
      - shortuuid
      - modelscope
      - vllm==v0.6.4.post1
      - cachetools
      - asyncache
      - https://github.com/noooop/wde/archive/refs/heads/main.zip
