name: wde
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - anaconda
  - pip
  - pip:
      - torch==2.6.0
      - torchvision==0.21.0
      - transformers==4.51.0
      - vllm==v0.8.3
      - fastapi
      - easydict
      - pydantic
      - pyzmq
      - gevent
      - uvicorn
      - shortuuid
      - modelscope
      - cachetools
      - asyncache
      - openai
      - ollama
      - https://github.com/noooop/wde/archive/refs/heads/main.zip
